import type { Metadata } from "next";
import { Toaster } from "sonner";
import { FetchNotes } from "@/components/layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Notes app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Toaster position="top-right" />
        <FetchNotes>{children}</FetchNotes>
      </body>
    </html>
  );
}
